name: Java CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          cache: gradle
      - name: clean build
        run: ./gradlew build clean test --info --stacktrace
